### ISSUE TITLE
Create a contact info block

### ISSUE THREAD

**Issue by KoshysDev** [KoshysDev/homepage#2]
Add links to social networks (LinkedIn, Facebook, Instagram), phone number, email, Telegram username, etc.

**Comment by KoshysDev** [comment]
#19

**Comment by KoshysDev** [comment]
To provide essential contact information in your resume, we will create a contact info block. This block will include various ways for potential employers or collaborators to get in touch with you. Here's an example:

**Contact Info Example:**
- Telegram: @koshys
- Instagram: @koshys.osu
- Email: koshys.osu@gmail.com

**To-Dos:**
- [x] Include your Telegram username as a contact method.
- [x] Add your Instagram handle for professional networking.
- [x] Provide your email address for communication purposes.
